blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # Url for blog index page
    path("blog_index/", views.blog_index, name='blog_index'),
    # Url for blog detail page
    path('blog_detail/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    # Url for blog category page
    path('blog_category/<category>/', views.blog_category, name='blog_category')
]

myportfolio/urls.py
from django.urls import path
from myportfolio import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'myportfolio'
urlpatterns = [
    # Url for index page
    path('', views.index, name='index'),
    # Url for single project detail
    path('project_detail/<int:project_id>/', views.project_detail, name='project_detail'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myportfolio.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path, include

app_name = 'user'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=20)


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    create_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', related_name='posts')


class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

myportfolio/models.py
from django.db import models


# Create your models here.

class MyPortfolio(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.FilePathField(path="D:\\pycharm\\portfolio\\static")

user/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    author = forms.CharField(max_length=60,
                             widget=forms.TextInput(attrs=
                                                    {'class': 'form-control',
                                                     'placeholder': 'Your Name'}))
    body = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Leave a Comment'
    }))

blog/views.py
from django.shortcuts import render
from blog.models import Post, Comment
from .forms import CommentForm


# Create your views here.
def blog_index(request):
    posts = Post.objects.all().order_by('-create_on')
    context = {"posts": posts, }
    return render(request, "blog_index.html", context)


def blog_category(request, category):
    posts = Post.objects.filter(categories__name__contains=category) \
        .order_by('-create_on')
    context = {
        'category': category,
        'posts': posts,
    }
    return render(request, 'blog_category.html', context)


def blog_detail(request, blog_id):
    post = Post.objects.get(id=blog_id)
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data['author'],
                body=form.cleaned_data['body'],
                post=post
            )
            comment.save()
    comments = Comment.objects.filter(post=post)
    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }
    return render(request, 'blog_detail.html', context)

myportfolio/views.py
from django.shortcuts import render
from .models import MyPortfolio


# Create your views here.

def index(request):
    projects = MyPortfolio.objects.all()
    context = {'projects': projects}
    return render(request, 'index.html', context)


def project_detail(request, project_id):
    project = MyPortfolio.objects.get(id=project_id)
    context = {'project': project}
    return render(request, 'project_detail.html', context)

user/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Portfolio</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'myportfolio:index' %}">My Portfolio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'myportfolio:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a href="{% url 'blog:blog_index' %}" class="nav-link">Blog</a>
      </li>
      <li class="nav-item">
          {% if user.is_authenticated %}
              <a href="{% url 'user:logout' %}" class="nav-link">Logout</a>
          {% else %}
            <a href="{% url 'user:login' %}" class="nav-link">Login</a>
          {% endif %}
      </li>
    </ul>
  </div>
</nav>
{% block content %}{% endblock content %}
</body>
</html>

templates/blog_category.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="col-md-8 offset-md-2">
    <h1>{{ category | title }}</h1>
    <hr>
    {% for post in posts %}
        <h2><a href="{% url 'blog:blog_detail' post.id %}">{{ post.title }}</a></h2>
        <small>
            {{ post.create_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'blog:blog_category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

templates/blog_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="row">
        <div class="offset-2"></div>
        <div class="col-8 mt-3">
            <h1>{{ post.title }}</h1>
    <small>
        {{ post.create_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog:blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | linebreaks }}</p>
    <h3>Leave a comment:</h3>
        <div class="col-6">
          <form action="{% url 'blog:blog_detail' post.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.author }}
            </div>
            <div class="form-group">
                {{ form.body }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
          <h3>Comments:</h3>
    {% for comment in comments %}
    <p>
        On {{comment.created_on.date }}&nbsp;
        <b>{{ comment.author }}</b> wrote:
    </p>
    <p>{{ comment.body }}</p>
    <hr>
    {% endfor %}
        </div>
        <div class="offset-2"></div>
    </div>
{% endblock %}

templates/blog_index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="col-md-8 offset-md-2">
    <h1>Blog Index</h1>
    <hr>
    {% for post in posts %}
    <h2><a href="{% url 'blog:blog_detail' post.id %}">{{ post.title }}</a></h2>
    <small>
        {{ post.create_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog:blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
            <h1>Projects</h1>
<div class="row">
{% for project in projects %}
    <div class="col-md-4">
        <div class="card mb-2">
            <img class="card-img-top" src="{% static project.image %}">
            <div class="card-body">
                <h5 class="card-title">{{ project.title }}</h5>
                <p class="card-text">{{ project.description }}</p>
                <a href="{% url 'myportfolio:project_detail' project.id %}"
                   class="btn btn-primary">
                    Read More
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>
{% endblock content %}

templates/project_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
<h1>{{ project.title }}</h1>
<div class="row">
    <div class="col-md-8">
        <img src="{% static project.image %}" alt="" width="100%">
    </div>
    <div class="col-md-4">
        <h5>About the project:</h5>
        <p>{{ project.description }}</p>
        <br>
        <h5>Technology used:</h5>
        <p>{{ project.technology }}</p>
    </div>
</div>
</div>
{% endblock content %}